Repository SeleniumHQ/docker-selenium, pull requests merged in 2024-10, with the labels that each got.

#2420 Fix node.lifecycle not being rendered from values file
  charts/selenium-grid/templates/_helpers.tpl
Labels: Review effort [1-5]: 2, Bug fix

#2425 chart(feat): add graphql metrics exporter for monitoring
  Base/Dockerfile
  Makefile
  NodeBase/Dockerfile
  README.md
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/configs/scrape/selenium-grid.yaml
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/_nameHelpers.tpl
  charts/selenium-grid/templates/monitoring-exporter-deployment.yaml
  charts/selenium-grid/templates/monitoring-exporter-service.yaml
  charts/selenium-grid/templates/monitoring-scape-secret.yaml
  charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml
  charts/selenium-grid/templates/trigger-auth.yaml
  charts/selenium-grid/values.yaml
  tests/SeleniumTests/__init__.py
  tests/charts/ci/base-tls-values.yaml
  tests/charts/make/chart_setup_env.sh
  tests/charts/templates/render/dummy.yaml
  tests/charts/templates/render/dummy_solution.yaml
Labels: enhancement, tests, Review effort [1-5]: 3

#2429 chart(update): use podIP in all components server host
  .github/workflows/helm-chart-test.yml
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/distributor-deployment.yaml
  charts/selenium-grid/templates/event-bus-deployment.yaml
  charts/selenium-grid/templates/hub-deployment.yaml
  charts/selenium-grid/templates/router-deployment.yaml
  charts/selenium-grid/templates/session-map-deployment.yaml
  charts/selenium-grid/templates/session-queue-deployment.yaml
  charts/selenium-grid/values.yaml
  tests/charts/make/chart_cluster_setup.sh
Labels: enhancement, configuration changes, Review effort [1-5]: 3

#2430 chart(update): Node deployment replicas use minReplicaCount in autoscaling
  .circleci/config.yml
  Makefile
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/Chart.yaml
  charts/selenium-grid/templates/chrome-node-deployment.yaml
  charts/selenium-grid/templates/edge-node-deployment.yaml
  charts/selenium-grid/templates/firefox-node-deployment.yaml
  charts/selenium-grid/values.yaml
  tests/SeleniumTests/__init__.py
  tests/charts/make/chart_test.sh
  tests/charts/templates/test.py
Labels: enhancement, tests, Review effort [1-5]: 3

#2437 fix: bash avoiding newline when Base64 encoding a long string
  Base/check-grid.sh
  Makefile
  Video/validate_endpoint.sh
  Video/video.sh
  Video/video_graphQLQuery.sh
  charts/selenium-grid/configs/distributor/distributorProbe.sh
  charts/selenium-grid/configs/node/nodeGridUrl.sh
  charts/selenium-grid/configs/node/nodePreStop.sh
  charts/selenium-grid/configs/node/nodeProbe.sh
  charts/selenium-grid/configs/router/routerProbe.sh
  tests/CDPTests/bootstrap.sh
Labels: Review effort [1-5]: 2

#2439 Update FFmpeg v7.1
  Makefile
Labels: enhancement

#2440 fix: clear CRIT message from supervisord
  Base/supervisord.conf
Labels: Bug fix, Review effort [1-5]: 1

#2443 fix: install dependencies for websockify utils in novnc
  Base/Dockerfile
  NodeBase/Dockerfile
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#2445 chart: Allow overwrite config videoRecorder in each node
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/chrome-node-deployment.yaml
  charts/selenium-grid/templates/chrome-node-scaledjobs.yaml
  charts/selenium-grid/templates/edge-node-deployment.yaml
  charts/selenium-grid/templates/edge-node-scaledjob.yaml
  charts/selenium-grid/templates/firefox-node-deployment.yaml
  charts/selenium-grid/templates/firefox-node-scaledjob.yaml
  charts/selenium-grid/values.yaml
  tests/charts/templates/render/dummy.yaml
  tests/charts/templates/render/dummy_solution.yaml
  tests/charts/templates/test.py
Labels: Review effort [1-5]: 3

#2450 [test] Include python binding Nightly to detect impact early
  Makefile
  tests/SeleniumTests/__init__.py
  tests/bootstrap.sh
Labels: Review effort [1-5]: 3
