Repository SeleniumHQ/docker-selenium, pull requests merged in 2024-06, with the labels that each got.

#2252 Upgrade Docker base image Ubuntu 22 -> Ubuntu 24
  Base/Dockerfile
Labels: enhancement, Review effort [1-5]: 2

#2287 Update FFmpeg 7.0.1
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  Makefile
  Video/Dockerfile
  Video/entry_point.sh
  Video/video.sh
  Video/video_graphQLQuery.sh
  tests/docker-compose-v3-test-node-docker.yaml
  tests/docker-compose-v3-test-node-relay.yml
  tests/docker-compose-v3-test-parallel.yml
  tests/docker-compose-v3-test-video.yml
  update_tag_in_docs_and_files.sh
Labels: enhancement, tests, configuration changes, Review effort [1-5]: 4

#2289 build: cleanup disk and increase timeout for deploy multi-arch images
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
Labels: enhancement, Review effort [1-5]: 2, Bug fix
