Repository SeleniumHQ/docker-selenium, pull requests merged in 2024-12, with the labels that each got.

#2484 K8s: regression issue on template for nodes service.enabled
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/chrome-node-service.yaml
  charts/selenium-grid/templates/firefox-node-service.yaml
  tests/charts/templates/render/dummy.yaml
  tests/charts/templates/render/dummy_solution.yaml
Labels: Review effort [1-5]: 2

#2488 Docker: Update Firefox binary installed in node
  Makefile
  NodeFirefox/Dockerfile
  README.md
Labels: Review effort [1-5]: 3

#2489 Docker: Node env vars to disable/enable VNC view only, password
  NodeBase/start-vnc.sh
  README.md
Labels: Review effort [1-5]: 1

#2490 K8s: Add test results for Grid autoscaling with KEDA
  .github/workflows/k8s-scaling-test.yml
  .keda/README.md
  .keda/results_test_k8s_autoscaling_deployment_count.md
  .keda/results_test_k8s_autoscaling_deployment_count_in_chaos.md
  .keda/results_test_k8s_autoscaling_deployment_count_with_node_max_sessions.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_in_chaos.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_with_node_max_sessions.md
  .keda/scalers/selenium_grid_scaler.go
  .keda/scalers/selenium_grid_scaler_test.go
  Makefile
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/values.yaml
  tests/AutoscalingTests/__init__.py
  tests/AutoscalingTests/common.py
  tests/AutoscalingTests/test_scale_chaos.py
  tests/AutoscalingTests/test_scale_up.py
  tests/README.md
  tests/bootstrap.sh
  tests/charts/ci/DeploymentAutoscaling-values.yaml
  tests/charts/ci/JobAutoscaling-values.yaml
  tests/charts/ci/base-recorder-values.yaml
  tests/charts/make/chart_test.sh
  tests/requirements.txt
Labels: Review effort [1-5]: 4

#2501 Correct kubectl cli params in keda patch job
  charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml
Labels: Review effort [1-5]: 1

#2520 Docker: set/unset stereotype via env var SE_NODE_BROWSER_VERSION and SE_BROWSER_BINARY_LOCATION
  NodeBase/Dockerfile
  NodeBase/generate_config
  Standalone/generate_config
  tests/docker-compose-v3-test-parallel.yml
  tests/docker-compose-v3-test-standalone.yml
Labels: Review effort [1-5]: 2

#2525 Docker: set/unset stereotype via env var SE_NODE_PLATFORM_NAME
  NodeBase/Dockerfile
  NodeBase/generate_config
Labels: Review effort [1-5]: 2

#2515 K8s: Selenium Grid in case multiple scaler triggers are activate
  .github/workflows/build-test.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/k8s-scaling-test.yml
  .keda/README.md
  Makefile
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/cross-browsers-values.yaml
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/values.yaml
  generate_chart_changelog.sh
  tests/AutoscalingTests/common.py
  tests/CDPTests/bootstrap.sh
  tests/SeleniumTests/__init__.py
  tests/charts/make/chart_test.sh
Labels: Review effort [1-5]: 3

#2486 [ci] Upload autoscaling in K8s test results
  .keda/results_test_k8s_autoscaling_deployment_count.md
  .keda/results_test_k8s_autoscaling_deployment_count_in_chaos.md
  .keda/results_test_k8s_autoscaling_deployment_count_with_node_max_sessions.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_in_chaos.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_with_node_max_sessions.md
Labels: Review effort [1-5]: 2

#2531 K8s: Autoscaling using KEDA core 2.16.1
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .github/workflows/helm-chart-release.yml
  .github/workflows/k8s-scaling-test.yml
  .github/workflows/update-chart-readme.yml
  .keda/README.md
  Makefile
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/Chart.yaml
  charts/selenium-grid/values.yaml
  generate_chart_changelog.sh
  tests/charts/make/chart_test.sh
Labels: Review effort [1-5]: 2

#2527 Docker: Improve the video recording container graceful shutdown
  Video/video.sh
  charts/selenium-grid/values.yaml
Labels: Review effort [1-5]: 3

#2534 Docker: Process of xvfb_vnc_novnc start by env variable
  NodeBase/selenium.conf
  tests/AutoscalingTests/common.py
Labels: Review effort [1-5]: 2

#2541 Docker: Update condition to enable tracing to avoid annoying warning messages
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
  docker-compose-v2.yml
  docker-compose-v3-basicauth.yml
  docker-compose-v3-beta-channel.yml
  docker-compose-v3-dev-channel.yml
  docker-compose-v3-dev.yml
  docker-compose-v3-dynamic-grid.yml
  docker-compose-v3-full-grid-dev.yml
  docker-compose-v3-full-grid-external-datastore.yml
  docker-compose-v3-full-grid-nightly.yml
  docker-compose-v3-full-grid-secure.yml
  docker-compose-v3-full-grid-swarm.yml
  docker-compose-v3-full-grid.yml
  docker-compose-v3-swarm.yml
  docker-compose-v3-video-in-node.yml
  docker-compose-v3-video-upload-dynamic-grid.yml
  docker-compose-v3-video-upload-standalone.yml
  docker-compose-v3-video-upload.yml
  docker-compose-v3-video.yml
  docker-compose-v3.yml
  tests/docker-compose-v3-test-node-docker.yaml
  tests/docker-compose-v3-test-node-relay.yml
  tests/docker-compose-v3-test-parallel.yml
  tests/docker-compose-v3-test-standalone-docker.yaml
  tests/docker-compose-v3-test-standalone.yml
  tests/docker-compose-v3-test-video.yml
Labels: Review effort [1-5]: 2

#2543 K8s: Add default values for multiple nodes platform and version
  Makefile
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/README.md
  charts/selenium-grid/multiple-nodes-platform-version.yaml
  charts/selenium-grid/multiple-nodes-platform.yaml
  charts/selenium-grid/values.yaml
  tests/SeleniumTests/__init__.py
  tests/charts/bootstrap.sh
  tests/charts/make/chart_test.sh
Labels: Review effort [1-5]: 3

#2545 K8s: Allow extra data set to EventBus and Node configmap
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/event-bus-configmap.yaml
  charts/selenium-grid/templates/node-configmap.yaml
  charts/selenium-grid/values.yaml
  tests/charts/templates/test.py
Labels: Review effort [1-5]: 2
