Repository SeleniumHQ/docker-selenium, pull requests merged in 2024-08, with the labels that each got.

#2337 update: handle graceful shutdown in Node container
  .gitignore
  Base/Dockerfile
  Base/entry_point.sh
  Makefile
  NodeBase/selenium.conf
  NodeChromium/Dockerfile
  Video/supervisord.conf
  charts/selenium-grid/configs/distributor/distributorProbe.sh
  charts/selenium-grid/configs/node/nodeGridUrl.sh
  charts/selenium-grid/configs/node/nodePreStop.sh
  charts/selenium-grid/configs/node/nodeProbe.sh
  charts/selenium-grid/configs/router/routerProbe.sh
  charts/selenium-grid/values.yaml
  tests/SeleniumTests/__init__.py
  tests/charts/make/chart_test.sh
  tests/docker-compose-v3-test-parallel.yml
Labels: enhancement, tests, Review effort [1-5]: 4

#2339 feat(chart): add support for revisionhistorylimit
  charts/selenium-grid/templates/chrome-node-deployment.yaml
  charts/selenium-grid/templates/distributor-deployment.yaml
  charts/selenium-grid/templates/edge-node-deployment.yaml
  charts/selenium-grid/templates/event-bus-deployment.yaml
  charts/selenium-grid/templates/firefox-node-deployment.yaml
  charts/selenium-grid/templates/hub-deployment.yaml
  charts/selenium-grid/templates/router-deployment.yaml
  charts/selenium-grid/templates/session-map-deployment.yaml
  charts/selenium-grid/templates/session-queue-deployment.yaml
  charts/selenium-grid/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#2342 feat: add support for structure logs
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
  charts/selenium-grid/templates/logging-configmap.yaml
  charts/selenium-grid/values.yaml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#2343 fix!: harmonized mount points to /opt/selenium/config.toml
  NodeDocker/start-selenium-grid-docker.sh
  README.md
  StandaloneDocker/start-selenium-grid-docker.sh
  docker-compose-v3-dynamic-grid.yml
  tests/docker-compose-v3-test-node-docker.yaml
Labels: enhancement, Review effort [1-5]: 2, documentation

#2344 add: secure connection for docker compose
  .gitignore
  Base/Dockerfile
  Base/entry_point.sh
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  Makefile
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  README.md
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
  charts/selenium-grid/.helmignore
  charts/selenium-grid/README.md
  charts/selenium-grid/certs/add-cert-helper.sh
  charts/selenium-grid/certs/add-jks-helper.sh
  charts/selenium-grid/certs/gen-cert-helper.sh
  charts/selenium-grid/certs/server.jks
  charts/selenium-grid/certs/server.pass
  charts/selenium-grid/certs/tls.crt
  charts/selenium-grid/certs/tls.key
  charts/selenium-grid/configs/distributor/distributorProbe.sh
  charts/selenium-grid/configs/node/nodePreStop.sh
  charts/selenium-grid/configs/node/nodeProbe.sh
  charts/selenium-grid/configs/router/routerProbe.sh
  charts/selenium-grid/templates/server-configmap.yaml
  charts/selenium-grid/values.yaml
  docker-compose-v3-full-grid-secure.yml
  tests/charts/make/chart_test.sh
  tests/customCACert/Dockerfile
  tests/customCACert/bootstrap.sh
  tests/customCACert/cert-script.sh
  tests/docker-compose-v3-test-parallel.yml
Labels: enhancement, tests, Review effort [1-5]: 4, documentation

#2345 fix: conflict config.toml in browser containers when node-docker volumes is shared
  Makefile
  NodeDocker/Dockerfile
  NodeDocker/start-selenium-grid-docker.sh
  README.md
  tests/SeleniumTests/__init__.py
  tests/docker-compose-v3-test-node-docker.yaml
Labels: enhancement, Review effort [1-5]: 2, Bug fix, documentation

#2346 update: Enable reject-unsupported-caps in standalone by default
  Standalone/Dockerfile
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
Labels: enhancement, configuration changes

#2347 update: Tracing is enabled by default
  Base/Dockerfile
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
  charts/selenium-grid/README.md
  charts/selenium-grid/templates/logging-configmap.yaml
  charts/selenium-grid/values.yaml
  tests/charts/make/chart_test.sh
Labels: enhancement, documentation, Review effort [1-5]: 3

#2349 chart(breaking change): update config key to enable ingress
  .github/workflows/deploy.yml
  .github/workflows/docker-test.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/rerun-failed.yml
  Makefile
  charts/selenium-grid/Chart.yaml
  charts/selenium-grid/README.md
  charts/selenium-grid/templates/NOTES.txt
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/ingress.yaml
  charts/selenium-grid/values.yaml
  generate_release_notes.sh
  tests/charts/ci/base-auth-ingress-values.yaml
  tests/charts/make/chart_setup_env.sh
  tests/charts/make/chart_test.sh
  tests/charts/refValues/sample-aws.yaml
  tests/charts/refValues/simplex-minikube.yaml
Labels: enhancement, tests, Review effort [1-5]: 4, documentation

#2352 fix: upload pipe detection
  Video/upload.sh
Labels: Bug fix, Review effort [1-5]: 3

#2359 Do not print secrets such as registration secret and router password to console on selenium grid hub and router startup
  Hub/start-selenium-grid-hub.sh
  Router/start-selenium-grid-router.sh
Labels: Review effort [1-5]: 2, Bug fix

#2360 fix: mask secret info from bash logs
  Base/Dockerfile
  Base/mask
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  README.md
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
Labels: Review effort [1-5]: 2, Bug fix, documentation
