Repository SeleniumHQ/docker-selenium, pull requests merged in 2024-04, with the labels that each got.

#2192 Correctly apply fix for high ulimit
  NodeBase/start-novnc.sh
  NodeBase/start-vnc.sh
Labels: bug_fix, Review effort [1-5]: 2

#2212 build: optimize image layers in base images
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/nightly.yaml
  .github/workflows/test-video.yml
  Base/Dockerfile
  Makefile
  NodeBase/Dockerfile
Labels: enhancement, configuration changes, Review effort [1-5]: 4

#2216 build: support download older Chrome version
  NodeChrome/Dockerfile
Labels: enhancement, Review effort [1-5]: 2

#2217 [build][doc]: upgrade browser with remain on same the Selenium version
  Makefile
  README.md
Labels: enhancement, Review effort [1-5]: 2, documentation

#2218 [build][doc]: build images with combination Grid and browser versions
  NodeChrome/Dockerfile
  NodeEdge/Dockerfile
  README.md
  tag_and_push_browser_images.sh
  tests/build-backward-compatible/bootstrap.sh
  tests/build-backward-compatible/builder.py
  tests/build-backward-compatible/cdp-matrix.yml
  tests/build-backward-compatible/selenium-matrix.yml
Labels: enhancement, documentation, Review effort [1-5]: 3

#2222 fix(chart): job to patch scaledobject stuck in deleting
  .github/workflows/build-test.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/test-video.yml
  Base/Dockerfile
  charts/selenium-grid/templates/_nameHelpers.tpl
  charts/selenium-grid/templates/chrome-node-hpa.yaml
  charts/selenium-grid/templates/chrome-node-scaledjobs.yaml
  charts/selenium-grid/templates/edge-node-hpa.yaml
  charts/selenium-grid/templates/edge-node-scaledjob.yaml
  charts/selenium-grid/templates/firefox-node-hpa.yaml
  charts/selenium-grid/templates/firefox-node-scaledjob.yaml
  charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml
  charts/selenium-grid/templates/patch-keda/patch-keda-rb.yaml
  charts/selenium-grid/templates/patch-keda/patch-keda-role.yaml
  charts/selenium-grid/values.yaml
  tests/charts/make/chart_test.sh
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2223 Release 4.20.0
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/nightly.yaml
  .github/workflows/test-video.yml
  Makefile
  tests/build-backward-compatible/selenium-matrix.yml
Labels: enhancement, configuration changes, Review effort [1-5]: 3

#2229 [build]: use docker buildx
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/nightly.yaml
  .github/workflows/test-video.yml
  .github/workflows/update-dev-beta-browser-images.yml
  Base/Dockerfile
  Makefile
  NodeBase/Dockerfile
Labels: enhancement, Review effort [1-5]: 4
