Repository SeleniumHQ/docker-selenium, pull requests merged in 2024-03, with the labels that each got.

#2167 fix: remove duplicate annotation
  charts/selenium-grid/values.yaml
Labels: bug_fix, Review effort [1-5]: 2

#2173 Added cleanup script for hanging Chrome processes and temp files
  NodeBase/Dockerfile
  NodeChrome/Dockerfile
  NodeChrome/chrome-cleanup.conf
  NodeChrome/chrome-cleanup.sh
  NodeEdge/Dockerfile
  NodeEdge/edge-cleanup.conf
  NodeEdge/edge-cleanup.sh
  NodeFirefox/Dockerfile
  NodeFirefox/firefox-cleanup.conf
  NodeFirefox/firefox-cleanup.sh
  README.md
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#2176 Use empty strings as defaults for some empty values
  charts/selenium-grid/values.yaml
Labels: bug_fix, Review effort [1-5]: 2

#2177 test: add test for node docker (dynamic grid)
  .github/workflows/test-video.yml
  Makefile
  tests/bootstrap.sh
  tests/charts/make/chart_setup_env.sh
  tests/config.toml
  tests/docker-compose-v3-test-node-docker.yaml
Labels: enhancement, Review effort [1-5]: 2, tests
