Repository SeleniumHQ/docker-selenium, pull requests merged in 2024-05, with the labels that each got.

#2239 fix(chart): RBAC settings for job patch finalizers
  charts/selenium-grid/README.md
  charts/selenium-grid/templates/_nameHelpers.tpl
  charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml
  charts/selenium-grid/templates/patch-keda/patch-keda-rb.yaml
  charts/selenium-grid/templates/patch-keda/patch-keda-role.yaml
  charts/selenium-grid/templates/rbac-role.yaml
  charts/selenium-grid/templates/rbac-rolebinding.yaml
  charts/selenium-grid/values.yaml
  tests/charts/make/chart_setup_env.sh
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#2245 update: browserleftoverscleanup conf star using env var
  NodeChrome/chrome-cleanup.conf
  NodeEdge/edge-cleanup.conf
  NodeFirefox/firefox-cleanup.conf
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#2247 update: Rollback FFmpeg v6.1.1
  Makefile
  NodeDocker/config.toml
  README.md
  charts/selenium-grid/README.md
  charts/selenium-grid/values.yaml
  docker-compose-v3-video-upload.yml
  docker-compose-v3-video.yml
  tests/SeleniumTests/__init__.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#2243 start pulseaudio in standalone mode
  Standalone/start-selenium-standalone.sh
Labels: enhancement, Review effort [1-5]: 2

#2249 feat: Video recording with dynamic file name based on metadata in tests
  .github/workflows/helm-chart-test.yml
  .github/workflows/test-video.yml
  Makefile
  NodeBase/Dockerfile
  README.md
  Video/Dockerfile
  Video/upload.sh
  Video/video.sh
  Video/video_graphQLQuery.sh
  charts/selenium-grid/README.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/recorder-configmap.yaml
  docker-compose-v3-video-upload.yml
  docker-compose-v3-video.yml
  tests/SeleniumTests/__init__.py
  tests/charts/ci/NoAutoscaling-values.yaml
  tests/charts/ci/NodeChrome-values.yaml
  tests/charts/ci/NodeEdge-values.yaml
  tests/charts/ci/NodeFirefox-values.yaml
  tests/charts/ci/base-recorder-values.yaml
  tests/charts/ci/local-pvc.yaml
  tests/charts/make/chart_test.sh
  tests/docker-compose-v3-test-node-docker.yaml
  tests/docker-compose-v3-test-video.yml
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#2254 [feat][test]: add env vars to generate config for Relay in node-base
  .github/workflows/build-test.yml
  .github/workflows/docker-test.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/nightly.yaml
  Makefile
  NodeBase/Dockerfile
  NodeBase/generate_config
  NodeBase/generate_relay_config
  NodeBase/start-selenium-node.sh
  README.md
  Standalone/start-selenium-standalone.sh
  tests/Dockerfile.emulator
  tests/SeleniumTests/__init__.py
  tests/docker-compose-v3-test-node-relay.yml
  tests/relay_config.toml
  tests/test.py
Labels: enhancement, tests, Review effort [1-5]: 4

#2266 [build][test]: Release docker images for aarch64 platform
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/build-test-multi-arch.yml
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .github/workflows/docker-test.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/nightly.yml
  .github/workflows/update-dev-beta-browser-images.yml
  Base/Dockerfile
  Makefile
  NodeBase/Dockerfile
  NodeChrome/Dockerfile
  NodeChromium/Dockerfile
  NodeChromium/chrome-cleanup.conf
  NodeChromium/chrome-cleanup.sh
  NodeEdge/Dockerfile
  NodeFirefox/Dockerfile
  NodeFirefox/Dockerfile.multi-arch
  NodeFirefox/README.md
  README.md
  Video/Dockerfile
  build-and-push.sh
  build-locally.sh
  charts/selenium-grid/CHANGELOG.md
  charts/selenium-grid/Chart.yaml
  docker-add-related-tags.sh
  generate_multi-arch-release_notes.sh
  generate_release_notes.sh
  get-access-token.py
  get-access-token.sh
  get-all-related-tags.go
  get-image-sha256-digest.go
  tag-and-push-multi-arch-image.sh
  tag_and_push_browser_images.sh
  tag_and_push_multi-arch_browser_images.sh
  tag_and_push_multi-arch_major_minor.sh
  tests/SeleniumTests/__init__.py
  tests/bootstrap.sh
  tests/build-backward-compatible/bootstrap.sh
  tests/charts/bootstrap.sh
  tests/charts/make/chart_build.sh
  tests/charts/make/chart_cluster_setup.sh
  tests/charts/make/chart_setup_env.sh
  tests/charts/make/chart_test.sh
  tests/config.toml
  tests/docker-compose-v3-test-node-relay.yml
  tests/docker-compose-v3-test-parallel.yml
  tests/relay_config.toml
  tests/test.py
Labels: enhancement, tests, Review effort [1-5]: 5

#2269 [test]: fix node relay tests
  .github/workflows/docker-test.yml
  Base/Dockerfile
  Makefile
  tests/docker-compose-v3-test-node-relay.yml
  tests/relay_config.toml
Labels: enhancement, tests

#2274 fix(chart): pod labels and annotations for patch-scaledobjects
  charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml
  tests/charts/ci/base-resources-values.yaml
Labels: enhancement, Review effort [1-5]: 2, Bug fix
