Repository SeleniumHQ/docker-selenium, pull requests merged in 2024-07, with the labels that each got.

#2300 docs: update readme on arm64 images
  README.md
Labels: Review effort [1-5]: 2, documentation

#2306 chart: refactoring config keys to enable secure connection
  Base/Dockerfile
  Makefile
  charts/selenium-grid/README.md
  charts/selenium-grid/certs/cert.sh
  charts/selenium-grid/certs/selenium.jks
  charts/selenium-grid/certs/selenium.pem
  charts/selenium-grid/certs/selenium.pkcs8.base64
  charts/selenium-grid/certs/server.jks
  charts/selenium-grid/certs/tls.crt
  charts/selenium-grid/certs/tls.key
  charts/selenium-grid/images/SeleniumGrid_TLS_SSL-Passthrough.png
  charts/selenium-grid/images/SeleniumGrid_TLS_SSL-Termination.png
  charts/selenium-grid/images/SeleniumGrid_TLS_WithoutProxy.png
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/distributor-deployment.yaml
  charts/selenium-grid/templates/event-bus-deployment.yaml
  charts/selenium-grid/templates/hub-deployment.yaml
  charts/selenium-grid/templates/ingress.yaml
  charts/selenium-grid/templates/node-configmap.yaml
  charts/selenium-grid/templates/router-deployment.yaml
  charts/selenium-grid/templates/secrets.yaml
  charts/selenium-grid/templates/server-configmap.yaml
  charts/selenium-grid/templates/session-map-deployment.yaml
  charts/selenium-grid/templates/session-queuer-deployment.yaml
  charts/selenium-grid/templates/tls-cert-secret.yaml
  charts/selenium-grid/values.yaml
  tests/charts/ci/base-recorder-values.yaml
  tests/charts/ci/base-tls-values.yaml
  tests/charts/make/chart_cluster_setup.sh
  tests/charts/make/chart_test.sh
  tests/customCACert/bootstrap.sh
Labels: enhancement, tests, Review effort [1-5]: 4, documentation

#2308 chart: proactive to set browser args via container env var
  NodeChrome/wrap_chrome_binary
  NodeChromium/wrap_chromium_binary
  NodeEdge/wrap_edge_binary
  README.md
  charts/selenium-grid/README.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/values.yaml
  tests/docker-compose-v3-test-node-docker.yaml
  tests/docker-compose-v3-test-parallel.yml
Labels: enhancement, documentation, Review effort [1-5]: 3

#2311 build: retry workflow and retry test on CircleCI
  .circleci/config.yml
  .github/workflows/build-test.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/rerun-failed.yml
Labels: enhancement, tests, Review effort [1-5]: 3

#2314 fix: warning LegacyKeyValueFormat in Dockerfile
  Base/Dockerfile
  Distributor/Dockerfile
  EventBus/Dockerfile
  Hub/Dockerfile
  NodeBase/Dockerfile
  NodeChrome/Dockerfile
  NodeChromium/Dockerfile
  NodeDocker/Dockerfile
  NodeEdge/Dockerfile
  NodeFirefox/Dockerfile
  Router/Dockerfile
  SessionQueue/Dockerfile
  Sessions/Dockerfile
  Standalone/Dockerfile
  StandaloneDocker/Dockerfile
  Video/Dockerfile
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#2316 build: dynamic fetch upstream build
  .circleci/config.yml
  .github/actions/get-latest-upstream/action.yml
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .github/workflows/docker-test.yml
  .github/workflows/helm-chart-release.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/nightly.yml
  Makefile
Labels: enhancement, configuration changes, Review effort [1-5]: 3

#2317 add: Env var SE_SUPERVISORD_LOG_LEVEL to set supervisord log level
  Base/Dockerfile
  Base/supervisord.conf
  Video/Dockerfile
  Video/supervisord.conf
  charts/selenium-grid/values.yaml
  tests/charts/ci/base-auth-ingress-values.yaml
  tests/docker-compose-v3-test-parallel.yml
  tests/docker-compose-v3-test-video.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#2319 chart(build): Push chart to Docker Hub OCI-based registry
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  Makefile
  tests/charts/make/chart_build.sh
  tests/charts/make/chart_release.sh
Labels: enhancement, tests, Review effort [1-5]: 3

#2323 chart(add): Set pod/container name to node stereotypes
  .circleci/config.yml
  .github/workflows/helm-chart-test.yml
  NodeBase/generate_config
  Standalone/generate_config
  charts/selenium-grid/templates/_helpers.tpl
  tests/charts/make/chart_setup_env.sh
Labels: enhancement, configuration changes, Review effort [1-5]: 3

#2325 build: get latest upstream build in release workflow
  .github/workflows/deploy.yml
  Makefile
  NodeChrome/Dockerfile
  NodeChromium/Dockerfile
  NodeEdge/Dockerfile
  tests/charts/make/chart_test.sh
Labels: enhancement, configuration changes

#2326 chart(breaking change): enable TLS and default annotations for ingress
  .github/workflows/build-test.yml
  Makefile
  charts/selenium-grid/README.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/ingress.yaml
  charts/selenium-grid/templates/jaeger-ingress.yaml
  charts/selenium-grid/values.yaml
  tests/SmokeTests/__init__.py
  tests/charts/make/chart_test.sh
  tests/charts/refValues/simplex-minikube.yaml
Labels: enhancement, tests, Review effort [1-5]: 4, documentation

#2328 chart(add): Default ingress annotations for upstream keepalive, or disable HTTP/2
  Makefile
  charts/selenium-grid/README.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/values.yaml
  tests/charts/make/chart_test.sh
Labels: enhancement, documentation, Review effort [1-5]: 3

#2334 chart(update): update env vars and health check scripts
  Base/Dockerfile
  Hub/start-selenium-grid-hub.sh
  NodeBase/Dockerfile
  README.md
  Router/start-selenium-grid-router.sh
  Standalone/start-selenium-standalone.sh
  Video/Dockerfile
  charts/selenium-grid/configs/distributor/distributorProbe.sh
  charts/selenium-grid/configs/node/nodeGridUrl.sh
  charts/selenium-grid/configs/node/nodePreStop.sh
  charts/selenium-grid/configs/node/nodeProbe.sh
  charts/selenium-grid/configs/router/routerGraphQLUrl.sh
  charts/selenium-grid/configs/router/routerProbe.sh
  charts/selenium-grid/templates/distributor-configmap.yaml
  charts/selenium-grid/templates/distributor-deployment.yaml
  charts/selenium-grid/templates/hub-deployment.yaml
  charts/selenium-grid/templates/node-configmap.yaml
  charts/selenium-grid/templates/router-configmap.yaml
  charts/selenium-grid/templates/secrets.yaml
  charts/selenium-grid/templates/session-queue-deployment.yaml
  charts/selenium-grid/templates/session-queue-service.yaml
  charts/selenium-grid/values.yaml
Labels: enhancement, configuration changes, Review effort [1-5]: 3
