Repository SeleniumHQ/docker-selenium, pull requests merged in 2025-09, with the labels that each got.

#2946 Docker: Support switch binary Chrome/Chromium in Node/Standalone all browsers image
  Base/Dockerfile
  ENV_VARIABLES.md
  NodeBase/generate_config
  NodeChrome/Dockerfile
  NodeChromium/Dockerfile
  NodeEdge/Dockerfile
  NodeFirefox/Dockerfile
  README.md
  scripts/generate_list_env_vars/description.yaml
Labels: Review effort 2/5

#2949 [ci] CHANGELOG for Node/Standalone edge browser versions with Grid 4.35.0
  .github/workflows/release-edge-versions.yml
  CHANGELOG/4.35.0/edge_114.md
  CHANGELOG/4.35.0/edge_115.md
  CHANGELOG/4.35.0/edge_116.md
  CHANGELOG/4.35.0/edge_117.md
  CHANGELOG/4.35.0/edge_118.md
  CHANGELOG/4.35.0/edge_119.md
  CHANGELOG/4.35.0/edge_120.md
  CHANGELOG/4.35.0/edge_121.md
  CHANGELOG/4.35.0/edge_122.md
  CHANGELOG/4.35.0/edge_123.md
  CHANGELOG/4.35.0/edge_124.md
  CHANGELOG/4.35.0/edge_125.md
  CHANGELOG/4.35.0/edge_126.md
  CHANGELOG/4.35.0/edge_127.md
  CHANGELOG/4.35.0/edge_128.md
  CHANGELOG/4.35.0/edge_129.md
  CHANGELOG/4.35.0/edge_130.md
  CHANGELOG/4.35.0/edge_131.md
  CHANGELOG/4.35.0/edge_132.md
  CHANGELOG/4.35.0/edge_133.md
  CHANGELOG/4.35.0/edge_134.md
  CHANGELOG/4.35.0/edge_135.md
  CHANGELOG/4.35.0/edge_136.md
  CHANGELOG/4.35.0/edge_137.md
  CHANGELOG/4.35.0/edge_138.md
  tests/build-backward-compatible/browser-matrix.yml
Labels: Review effort 2/5

#2959 fix(doc): fix minor typo in Helm helper function (monitoring)
  charts/selenium-grid/templates/_helpers.tpl
Labels: Review effort 1/5

#2962 Docker: Remove pre-gen self-sign cert in image
  Base/Dockerfile
  Makefile
  NodeAllBrowsers/Dockerfile
Labels: Review effort 2/5

#2960 K8s: Switch image registry for Bitnami deps image in sub charts
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/values.yaml
Labels: Review effort 2/5, Possible security concern
