Repository SeleniumHQ/docker-selenium, pull requests merged in 2025-07, with the labels that each got.

#2873 [ci] Fetch latest version of dependencies
  README.md
  tests/charts/make/chart_setup_env.sh
Labels: Review effort 2/5

#2876 Docker: Add default value for env var `SE_NODE_GRID_URL`
  NodeBase/Dockerfile
Labels: Review effort 1/5

#2877 [ci] Change runner for deploy workflow
  .github/workflows/deploy.yml
Labels: Review effort 2/5

#2885 Docker: Update dependencies version
  .github/workflows/deploy.yml
  .github/workflows/nightly.yml
  Base/Dockerfile
  NodeChrome/install-chrome.sh
  NodeEdge/Dockerfile
Labels: Review effort 2/5

#2894 [ci] CHANGELOG for Node/Standalone firefox browser versions with Grid 4.34.0
  CHANGELOG/4.34.0/firefox_100.md
  CHANGELOG/4.34.0/firefox_101.md
  CHANGELOG/4.34.0/firefox_102.md
  CHANGELOG/4.34.0/firefox_103.md
  CHANGELOG/4.34.0/firefox_104.md
  CHANGELOG/4.34.0/firefox_105.md
  CHANGELOG/4.34.0/firefox_106.md
  CHANGELOG/4.34.0/firefox_107.md
  CHANGELOG/4.34.0/firefox_108.md
  CHANGELOG/4.34.0/firefox_109.md
  CHANGELOG/4.34.0/firefox_110.md
  CHANGELOG/4.34.0/firefox_111.md
  CHANGELOG/4.34.0/firefox_112.md
  CHANGELOG/4.34.0/firefox_113.md
  CHANGELOG/4.34.0/firefox_114.md
  CHANGELOG/4.34.0/firefox_115.md
  CHANGELOG/4.34.0/firefox_116.md
  CHANGELOG/4.34.0/firefox_117.md
  CHANGELOG/4.34.0/firefox_118.md
  CHANGELOG/4.34.0/firefox_119.md
  CHANGELOG/4.34.0/firefox_120.md
  CHANGELOG/4.34.0/firefox_121.md
  CHANGELOG/4.34.0/firefox_122.md
  CHANGELOG/4.34.0/firefox_123.md
  CHANGELOG/4.34.0/firefox_124.md
  CHANGELOG/4.34.0/firefox_125.md
  CHANGELOG/4.34.0/firefox_126.md
  CHANGELOG/4.34.0/firefox_127.md
  CHANGELOG/4.34.0/firefox_128.md
  CHANGELOG/4.34.0/firefox_129.md
  CHANGELOG/4.34.0/firefox_130.md
  CHANGELOG/4.34.0/firefox_131.md
  CHANGELOG/4.34.0/firefox_132.md
  CHANGELOG/4.34.0/firefox_133.md
  CHANGELOG/4.34.0/firefox_134.md
  CHANGELOG/4.34.0/firefox_135.md
  CHANGELOG/4.34.0/firefox_136.md
  CHANGELOG/4.34.0/firefox_137.md
  CHANGELOG/4.34.0/firefox_138.md
  CHANGELOG/4.34.0/firefox_139.md
  CHANGELOG/4.34.0/firefox_98.md
  CHANGELOG/4.34.0/firefox_99.md
  tests/build-backward-compatible/browser-matrix.yml
  tests/build-backward-compatible/firefox-matrix.yml
Labels: Review effort 1/5

#2907 [KEDA] Selenium Grid: Add trigger param `overProvisionRatio` for ability to scale more than queue request
  .keda/README.md
  .keda/scalers/selenium-grid-scaler.md
  .keda/scalers/selenium_grid_scaler.go
  .keda/scalers/selenium_grid_scaler_test.go
  Makefile
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/values.yaml
  tests/charts/ci/DeploymentAutoscaling-values.yaml
  tests/charts/templates/render/dummy.yaml
  tests/charts/templates/render/dummy_solution.yaml
Labels: Review effort 3/5
