Repository SeleniumHQ/docker-selenium, pull requests merged in 2025-02, with the labels that each got.

#2625 SE_NODE_RELAY_STEREOTYPE_EXTRA to append custom capabilities to default Relay stereotype
  ENV_VARIABLES.md
  Makefile
  NodeBase/generate_config
  NodeBase/generate_relay_config
  README.md
  scripts/generate_list_env_vars/description.yaml
  scripts/generate_list_env_vars/value.yaml
  tests/docker-compose-v3-test-node-relay.yml
  tests/relay_config.toml
Labels: Review effort [1-5]: 3

#2623 [ci] Upload CHANGELOG for Node/Standalone chrome version with Grid 4.28.1
  CHANGELOG/4.28.1/chrome_100.md
  CHANGELOG/4.28.1/chrome_101.md
  CHANGELOG/4.28.1/chrome_102.md
  CHANGELOG/4.28.1/chrome_103.md
  CHANGELOG/4.28.1/chrome_104.md
  CHANGELOG/4.28.1/chrome_105.md
  CHANGELOG/4.28.1/chrome_106.md
  CHANGELOG/4.28.1/chrome_107.md
  CHANGELOG/4.28.1/chrome_108.md
  CHANGELOG/4.28.1/chrome_109.md
  CHANGELOG/4.28.1/chrome_97.md
  CHANGELOG/4.28.1/chrome_98.md
  CHANGELOG/4.28.1/chrome_99.md
Labels: Review effort [1-5]: 1

#2626 feat: Deploy Node/Standalone Chrome browser version from v97 to v109 on top of Grid 4.28.1
  .github/workflows/release-chrome-versions.yml
  CHANGELOG/4.28.1/chrome_100.md
  CHANGELOG/4.28.1/chrome_101.md
  CHANGELOG/4.28.1/chrome_102.md
  CHANGELOG/4.28.1/chrome_103.md
  CHANGELOG/4.28.1/chrome_104.md
  CHANGELOG/4.28.1/chrome_105.md
  CHANGELOG/4.28.1/chrome_106.md
  CHANGELOG/4.28.1/chrome_107.md
  CHANGELOG/4.28.1/chrome_108.md
  CHANGELOG/4.28.1/chrome_109.md
  CHANGELOG/4.28.1/chrome_97.md
  CHANGELOG/4.28.1/chrome_98.md
  CHANGELOG/4.28.1/chrome_99.md
  charts/selenium-grid/multiple-nodes-platform-version.yaml
  tests/build-backward-compatible/bootstrap.sh
  tests/build-backward-compatible/builder.py
  tests/build-backward-compatible/cdp-matrix.yml
Labels: Review effort [1-5]: 3

#2627 [ci] Upload CHANGELOG for Node/Standalone edge version with Grid 4.28.1
  CHANGELOG/4.28.1/edge_114.md
  CHANGELOG/4.28.1/edge_115.md
  CHANGELOG/4.28.1/edge_116.md
  CHANGELOG/4.28.1/edge_117.md
  CHANGELOG/4.28.1/edge_118.md
  CHANGELOG/4.28.1/edge_119.md
  CHANGELOG/4.28.1/edge_120.md
  CHANGELOG/4.28.1/edge_121.md
  CHANGELOG/4.28.1/edge_122.md
  CHANGELOG/4.28.1/edge_123.md
  CHANGELOG/4.28.1/edge_124.md
  CHANGELOG/4.28.1/edge_125.md
  CHANGELOG/4.28.1/edge_126.md
  CHANGELOG/4.28.1/edge_127.md
  CHANGELOG/4.28.1/edge_128.md
  CHANGELOG/4.28.1/edge_129.md
  CHANGELOG/4.28.1/edge_130.md
  CHANGELOG/4.28.1/edge_131.md
  CHANGELOG/4.28.1/edge_132.md
Labels: Review effort [1-5]: 1

#2628 feat: Deploy Node/Standalone Edge browser version from v114 to v131
  CHANGELOG/4.28.1/edge_114.md
  CHANGELOG/4.28.1/edge_115.md
  CHANGELOG/4.28.1/edge_116.md
  CHANGELOG/4.28.1/edge_117.md
  CHANGELOG/4.28.1/edge_118.md
  CHANGELOG/4.28.1/edge_119.md
  CHANGELOG/4.28.1/edge_120.md
  CHANGELOG/4.28.1/edge_121.md
  CHANGELOG/4.28.1/edge_122.md
  CHANGELOG/4.28.1/edge_123.md
  CHANGELOG/4.28.1/edge_124.md
  CHANGELOG/4.28.1/edge_125.md
  CHANGELOG/4.28.1/edge_126.md
  CHANGELOG/4.28.1/edge_127.md
  CHANGELOG/4.28.1/edge_128.md
  CHANGELOG/4.28.1/edge_129.md
  CHANGELOG/4.28.1/edge_130.md
  CHANGELOG/4.28.1/edge_131.md
  CHANGELOG/4.28.1/edge_132.md
  Makefile
  tests/build-backward-compatible/bootstrap.sh
Labels: Review effort [1-5]: 2

#2629 Docker: Respect SE_SCREEN_{WIDTH,HEIGHT} variables in ffmpeg recording
  Video/Dockerfile
  Video/video.sh
Labels: Review effort [1-5]: 2

#2631 [ci] Upload CHANGELOG for Node/Standalone firefox version with Grid 4.28.1
  CHANGELOG/4.28.1/firefox_100.md
  CHANGELOG/4.28.1/firefox_101.md
  CHANGELOG/4.28.1/firefox_102.md
  CHANGELOG/4.28.1/firefox_103.md
  CHANGELOG/4.28.1/firefox_104.md
  CHANGELOG/4.28.1/firefox_105.md
  CHANGELOG/4.28.1/firefox_106.md
  CHANGELOG/4.28.1/firefox_107.md
  CHANGELOG/4.28.1/firefox_108.md
  CHANGELOG/4.28.1/firefox_109.md
  CHANGELOG/4.28.1/firefox_110.md
  CHANGELOG/4.28.1/firefox_111.md
  CHANGELOG/4.28.1/firefox_112.md
  CHANGELOG/4.28.1/firefox_113.md
  CHANGELOG/4.28.1/firefox_114.md
  CHANGELOG/4.28.1/firefox_115.md
  CHANGELOG/4.28.1/firefox_116.md
  CHANGELOG/4.28.1/firefox_117.md
  CHANGELOG/4.28.1/firefox_118.md
  CHANGELOG/4.28.1/firefox_119.md
  CHANGELOG/4.28.1/firefox_120.md
  CHANGELOG/4.28.1/firefox_121.md
  CHANGELOG/4.28.1/firefox_122.md
  CHANGELOG/4.28.1/firefox_123.md
  CHANGELOG/4.28.1/firefox_124.md
  CHANGELOG/4.28.1/firefox_125.md
  CHANGELOG/4.28.1/firefox_126.md
  CHANGELOG/4.28.1/firefox_127.md
  CHANGELOG/4.28.1/firefox_128.md
  CHANGELOG/4.28.1/firefox_129.md
  CHANGELOG/4.28.1/firefox_130.md
  CHANGELOG/4.28.1/firefox_131.md
  CHANGELOG/4.28.1/firefox_132.md
  CHANGELOG/4.28.1/firefox_133.md
  CHANGELOG/4.28.1/firefox_134.md
  CHANGELOG/4.28.1/firefox_98.md
  CHANGELOG/4.28.1/firefox_99.md
Labels: Review effort [1-5]: 2

#2632 feat: Deploy Node/Standalone Firefox browser version from v98 to v134
  .github/workflows/release-chrome-versions.yml
  .github/workflows/release-edge-versions.yml
  .github/workflows/release-firefox-versions.yml
  CHANGELOG/4.28.1/firefox_100.md
  CHANGELOG/4.28.1/firefox_101.md
  CHANGELOG/4.28.1/firefox_102.md
  CHANGELOG/4.28.1/firefox_103.md
  CHANGELOG/4.28.1/firefox_104.md
  CHANGELOG/4.28.1/firefox_105.md
  CHANGELOG/4.28.1/firefox_106.md
  CHANGELOG/4.28.1/firefox_107.md
  CHANGELOG/4.28.1/firefox_108.md
  CHANGELOG/4.28.1/firefox_109.md
  CHANGELOG/4.28.1/firefox_110.md
  CHANGELOG/4.28.1/firefox_111.md
  CHANGELOG/4.28.1/firefox_112.md
  CHANGELOG/4.28.1/firefox_113.md
  CHANGELOG/4.28.1/firefox_114.md
  CHANGELOG/4.28.1/firefox_115.md
  CHANGELOG/4.28.1/firefox_116.md
  CHANGELOG/4.28.1/firefox_117.md
  CHANGELOG/4.28.1/firefox_118.md
  CHANGELOG/4.28.1/firefox_119.md
  CHANGELOG/4.28.1/firefox_120.md
  CHANGELOG/4.28.1/firefox_121.md
  CHANGELOG/4.28.1/firefox_122.md
  CHANGELOG/4.28.1/firefox_123.md
  CHANGELOG/4.28.1/firefox_124.md
  CHANGELOG/4.28.1/firefox_125.md
  CHANGELOG/4.28.1/firefox_126.md
  CHANGELOG/4.28.1/firefox_127.md
  CHANGELOG/4.28.1/firefox_128.md
  CHANGELOG/4.28.1/firefox_129.md
  CHANGELOG/4.28.1/firefox_130.md
  CHANGELOG/4.28.1/firefox_131.md
  CHANGELOG/4.28.1/firefox_132.md
  CHANGELOG/4.28.1/firefox_133.md
  CHANGELOG/4.28.1/firefox_134.md
  CHANGELOG/4.28.1/firefox_98.md
  CHANGELOG/4.28.1/firefox_99.md
  Makefile
  NodeFirefox/Dockerfile
  NodeFirefox/get_lang_package.sh
  charts/selenium-grid/multiple-nodes-platform-version.yaml
  tests/SeleniumTests/__init__.py
  tests/build-backward-compatible/bootstrap.sh
  tests/build-backward-compatible/builder.py
  update_tag_in_docs_and_files.sh
Labels: Review effort [1-5]: 4

#2635 [ci] Upload CHANGELOG for Node/Standalone firefox version with Grid 4.28.1
  CHANGELOG/4.28.1/firefox_100.md
  CHANGELOG/4.28.1/firefox_101.md
  CHANGELOG/4.28.1/firefox_102.md
  CHANGELOG/4.28.1/firefox_103.md
  CHANGELOG/4.28.1/firefox_104.md
  CHANGELOG/4.28.1/firefox_105.md
  CHANGELOG/4.28.1/firefox_106.md
  CHANGELOG/4.28.1/firefox_107.md
  CHANGELOG/4.28.1/firefox_108.md
  CHANGELOG/4.28.1/firefox_109.md
  CHANGELOG/4.28.1/firefox_110.md
  CHANGELOG/4.28.1/firefox_111.md
  CHANGELOG/4.28.1/firefox_112.md
  CHANGELOG/4.28.1/firefox_113.md
  CHANGELOG/4.28.1/firefox_114.md
  CHANGELOG/4.28.1/firefox_115.md
  CHANGELOG/4.28.1/firefox_116.md
  CHANGELOG/4.28.1/firefox_117.md
  CHANGELOG/4.28.1/firefox_118.md
  CHANGELOG/4.28.1/firefox_119.md
  CHANGELOG/4.28.1/firefox_120.md
  CHANGELOG/4.28.1/firefox_121.md
  CHANGELOG/4.28.1/firefox_122.md
  CHANGELOG/4.28.1/firefox_123.md
  CHANGELOG/4.28.1/firefox_124.md
  CHANGELOG/4.28.1/firefox_125.md
  CHANGELOG/4.28.1/firefox_126.md
  CHANGELOG/4.28.1/firefox_127.md
  CHANGELOG/4.28.1/firefox_128.md
  CHANGELOG/4.28.1/firefox_129.md
  CHANGELOG/4.28.1/firefox_130.md
  CHANGELOG/4.28.1/firefox_131.md
  CHANGELOG/4.28.1/firefox_132.md
  CHANGELOG/4.28.1/firefox_133.md
  CHANGELOG/4.28.1/firefox_134.md
  CHANGELOG/4.28.1/firefox_98.md
  CHANGELOG/4.28.1/firefox_99.md
Labels: Review effort [1-5]: 1

#2636 [ci] Upload CHANGELOG for Node/Standalone chrome version with Grid 4.28.1
  CHANGELOG/4.28.1/chrome_100.md
  CHANGELOG/4.28.1/chrome_101.md
  CHANGELOG/4.28.1/chrome_102.md
  CHANGELOG/4.28.1/chrome_103.md
  CHANGELOG/4.28.1/chrome_104.md
  CHANGELOG/4.28.1/chrome_105.md
  CHANGELOG/4.28.1/chrome_106.md
  CHANGELOG/4.28.1/chrome_107.md
  CHANGELOG/4.28.1/chrome_108.md
  CHANGELOG/4.28.1/chrome_109.md
  CHANGELOG/4.28.1/chrome_110.md
  CHANGELOG/4.28.1/chrome_111.md
  CHANGELOG/4.28.1/chrome_112.md
  CHANGELOG/4.28.1/chrome_113.md
  CHANGELOG/4.28.1/chrome_114.md
  CHANGELOG/4.28.1/chrome_115.md
  CHANGELOG/4.28.1/chrome_116.md
  CHANGELOG/4.28.1/chrome_117.md
  CHANGELOG/4.28.1/chrome_118.md
  CHANGELOG/4.28.1/chrome_119.md
  CHANGELOG/4.28.1/chrome_120.md
  CHANGELOG/4.28.1/chrome_121.md
  CHANGELOG/4.28.1/chrome_122.md
  CHANGELOG/4.28.1/chrome_123.md
  CHANGELOG/4.28.1/chrome_124.md
  CHANGELOG/4.28.1/chrome_125.md
  CHANGELOG/4.28.1/chrome_126.md
  CHANGELOG/4.28.1/chrome_127.md
  CHANGELOG/4.28.1/chrome_128.md
  CHANGELOG/4.28.1/chrome_129.md
  CHANGELOG/4.28.1/chrome_130.md
  CHANGELOG/4.28.1/chrome_131.md
  CHANGELOG/4.28.1/chrome_132.md
  CHANGELOG/4.28.1/chrome_97.md
  CHANGELOG/4.28.1/chrome_98.md
  CHANGELOG/4.28.1/chrome_99.md
Labels: Review effort [1-5]: 1

#2639 [ci] CHANGELOG for Node/Standalone firefox browser versions with Grid 4.28.1
  CHANGELOG/4.28.1/firefox_100.md
  CHANGELOG/4.28.1/firefox_101.md
  CHANGELOG/4.28.1/firefox_102.md
  CHANGELOG/4.28.1/firefox_103.md
  CHANGELOG/4.28.1/firefox_104.md
  CHANGELOG/4.28.1/firefox_105.md
  CHANGELOG/4.28.1/firefox_106.md
  CHANGELOG/4.28.1/firefox_107.md
  CHANGELOG/4.28.1/firefox_108.md
  CHANGELOG/4.28.1/firefox_109.md
  CHANGELOG/4.28.1/firefox_110.md
  CHANGELOG/4.28.1/firefox_111.md
  CHANGELOG/4.28.1/firefox_112.md
  CHANGELOG/4.28.1/firefox_113.md
  CHANGELOG/4.28.1/firefox_114.md
  CHANGELOG/4.28.1/firefox_115.md
  CHANGELOG/4.28.1/firefox_116.md
  CHANGELOG/4.28.1/firefox_117.md
  CHANGELOG/4.28.1/firefox_118.md
  CHANGELOG/4.28.1/firefox_119.md
  CHANGELOG/4.28.1/firefox_120.md
  CHANGELOG/4.28.1/firefox_121.md
  CHANGELOG/4.28.1/firefox_122.md
  CHANGELOG/4.28.1/firefox_123.md
  CHANGELOG/4.28.1/firefox_124.md
  CHANGELOG/4.28.1/firefox_125.md
  CHANGELOG/4.28.1/firefox_126.md
  CHANGELOG/4.28.1/firefox_127.md
  CHANGELOG/4.28.1/firefox_128.md
  CHANGELOG/4.28.1/firefox_129.md
  CHANGELOG/4.28.1/firefox_130.md
  CHANGELOG/4.28.1/firefox_131.md
  CHANGELOG/4.28.1/firefox_132.md
  CHANGELOG/4.28.1/firefox_133.md
  CHANGELOG/4.28.1/firefox_134.md
  CHANGELOG/4.28.1/firefox_98.md
  CHANGELOG/4.28.1/firefox_99.md
Labels: Review effort [1-5]: 1

#2637 [ci] CHANGELOG for Node/Standalone chrome browser versions with Grid 4.28.1
  CHANGELOG/4.28.1/chrome_100.md
  CHANGELOG/4.28.1/chrome_101.md
  CHANGELOG/4.28.1/chrome_102.md
  CHANGELOG/4.28.1/chrome_103.md
  CHANGELOG/4.28.1/chrome_104.md
  CHANGELOG/4.28.1/chrome_105.md
  CHANGELOG/4.28.1/chrome_106.md
  CHANGELOG/4.28.1/chrome_107.md
  CHANGELOG/4.28.1/chrome_108.md
  CHANGELOG/4.28.1/chrome_109.md
  CHANGELOG/4.28.1/chrome_110.md
  CHANGELOG/4.28.1/chrome_111.md
  CHANGELOG/4.28.1/chrome_112.md
  CHANGELOG/4.28.1/chrome_113.md
  CHANGELOG/4.28.1/chrome_114.md
  CHANGELOG/4.28.1/chrome_115.md
  CHANGELOG/4.28.1/chrome_116.md
  CHANGELOG/4.28.1/chrome_117.md
  CHANGELOG/4.28.1/chrome_118.md
  CHANGELOG/4.28.1/chrome_119.md
  CHANGELOG/4.28.1/chrome_120.md
  CHANGELOG/4.28.1/chrome_121.md
  CHANGELOG/4.28.1/chrome_122.md
  CHANGELOG/4.28.1/chrome_123.md
  CHANGELOG/4.28.1/chrome_124.md
  CHANGELOG/4.28.1/chrome_125.md
  CHANGELOG/4.28.1/chrome_126.md
  CHANGELOG/4.28.1/chrome_127.md
  CHANGELOG/4.28.1/chrome_128.md
  CHANGELOG/4.28.1/chrome_129.md
  CHANGELOG/4.28.1/chrome_130.md
  CHANGELOG/4.28.1/chrome_131.md
  CHANGELOG/4.28.1/chrome_132.md
  CHANGELOG/4.28.1/chrome_97.md
  CHANGELOG/4.28.1/chrome_98.md
  CHANGELOG/4.28.1/chrome_99.md
Labels: Review effort [1-5]: 1

#2642 Update base to use JDK21
  Base/Dockerfile
Labels: Review effort [1-5]: 2

#2649 K8s: Update KEDA patch version for feature preview
  .keda/README.md
  .keda/scalers/selenium-grid-scaler.md
  .keda/scalers/selenium_grid_scaler.go
  .keda/scalers/selenium_grid_scaler_test.go
  Makefile
  tests/build-backward-compatible/cdp-matrix.yml
Labels: Review effort [1-5]: 2

#2651 [ci] Upload autoscaling in K8s test results
  .keda/results_test_k8s_autoscaling_deployment_count.md
  .keda/results_test_k8s_autoscaling_deployment_count_in_chaos.md
  .keda/results_test_k8s_autoscaling_deployment_count_with_node_max_sessions.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_in_chaos.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_with_node_max_sessions.md
Labels: Review effort [1-5]: 2

#2653 share system certificate support
  NodeBase/Dockerfile
Labels: Review effort [1-5]: 1

#2660 Fix add-cert-helper.sh only adding a single certificate in Chrome
  charts/selenium-grid/certs/add-cert-helper.sh
  tests/customCACert/bootstrap.sh
Labels: Review effort 2/5

#2661 K8s: Improve Node checks for liveness probe and preStop hook
  charts/selenium-grid/configs/node/nodePreStop.sh
  charts/selenium-grid/configs/node/nodeProbe.sh
Labels: Review effort 3/5

#2662 K8s: Default Node register period is longer with a short cycle
  ENV_VARIABLES.md
  NodeBase/Dockerfile
  NodeBase/generate_config
  NodeBase/start-selenium-node.sh
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/values.yaml
  scripts/generate_list_env_vars/description.yaml
  scripts/generate_list_env_vars/value.yaml
Labels: Review effort 2/5

#2666 Docker: Collect JVM heap dump only enable via env var
  Base/handle_heap_dump.sh
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
Labels: Review effort 2/5

#2667 Update Selenium Grid 4.29.0
  Makefile
Labels: Review effort 1/5

#2668 K8s: Set K8s node IP to all components via env var KUBERNETES_NODE_HOST_IP
  Base/Dockerfile
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  Makefile
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
  charts/selenium-grid/README.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/distributor-deployment.yaml
  charts/selenium-grid/templates/event-bus-deployment.yaml
  charts/selenium-grid/templates/hub-deployment.yaml
  charts/selenium-grid/templates/router-deployment.yaml
  charts/selenium-grid/templates/session-map-deployment.yaml
  charts/selenium-grid/templates/session-queue-deployment.yaml
  tests/charts/make/chart_test.sh
Labels: Review effort 2/5

#2673 [ci] CHANGELOG for Node/Standalone edge browser versions with Grid 4.29.0
  CHANGELOG/4.29.0/edge_114.md
  CHANGELOG/4.29.0/edge_115.md
  CHANGELOG/4.29.0/edge_116.md
  CHANGELOG/4.29.0/edge_117.md
  CHANGELOG/4.29.0/edge_118.md
  CHANGELOG/4.29.0/edge_119.md
  CHANGELOG/4.29.0/edge_120.md
  CHANGELOG/4.29.0/edge_121.md
  CHANGELOG/4.29.0/edge_122.md
  CHANGELOG/4.29.0/edge_123.md
  CHANGELOG/4.29.0/edge_124.md
  CHANGELOG/4.29.0/edge_125.md
  CHANGELOG/4.29.0/edge_126.md
  CHANGELOG/4.29.0/edge_127.md
  CHANGELOG/4.29.0/edge_128.md
  CHANGELOG/4.29.0/edge_129.md
  CHANGELOG/4.29.0/edge_130.md
  CHANGELOG/4.29.0/edge_131.md
  CHANGELOG/4.29.0/edge_132.md
  CHANGELOG/4.29.0/edge_133.md
Labels: Review effort 1/5

#2674 [ci] CHANGELOG for Node/Standalone firefox browser versions with Grid 4.29.0
  CHANGELOG/4.29.0/firefox_100.md
  CHANGELOG/4.29.0/firefox_101.md
  CHANGELOG/4.29.0/firefox_102.md
  CHANGELOG/4.29.0/firefox_103.md
  CHANGELOG/4.29.0/firefox_104.md
  CHANGELOG/4.29.0/firefox_105.md
  CHANGELOG/4.29.0/firefox_106.md
  CHANGELOG/4.29.0/firefox_107.md
  CHANGELOG/4.29.0/firefox_108.md
  CHANGELOG/4.29.0/firefox_109.md
  CHANGELOG/4.29.0/firefox_110.md
  CHANGELOG/4.29.0/firefox_111.md
  CHANGELOG/4.29.0/firefox_112.md
  CHANGELOG/4.29.0/firefox_113.md
  CHANGELOG/4.29.0/firefox_114.md
  CHANGELOG/4.29.0/firefox_115.md
  CHANGELOG/4.29.0/firefox_116.md
  CHANGELOG/4.29.0/firefox_117.md
  CHANGELOG/4.29.0/firefox_118.md
  CHANGELOG/4.29.0/firefox_119.md
  CHANGELOG/4.29.0/firefox_120.md
  CHANGELOG/4.29.0/firefox_121.md
  CHANGELOG/4.29.0/firefox_122.md
  CHANGELOG/4.29.0/firefox_123.md
  CHANGELOG/4.29.0/firefox_124.md
  CHANGELOG/4.29.0/firefox_125.md
  CHANGELOG/4.29.0/firefox_126.md
  CHANGELOG/4.29.0/firefox_127.md
  CHANGELOG/4.29.0/firefox_128.md
  CHANGELOG/4.29.0/firefox_129.md
  CHANGELOG/4.29.0/firefox_130.md
  CHANGELOG/4.29.0/firefox_131.md
  CHANGELOG/4.29.0/firefox_132.md
  CHANGELOG/4.29.0/firefox_133.md
  CHANGELOG/4.29.0/firefox_134.md
  CHANGELOG/4.29.0/firefox_98.md
  CHANGELOG/4.29.0/firefox_99.md
Labels: Review effort 2/5

#2675 Docker: Fix CVEs in dependencies
  .github/workflows/release-chrome-versions.yml
  .github/workflows/release-edge-versions.yml
  .github/workflows/release-firefox-versions.yml
  Base/Dockerfile
  tests/build-backward-compatible/bootstrap.sh
  tests/build-backward-compatible/browser-matrix.yml
  tests/charts/make/chart_setup_env.sh
Labels: Review effort 2/5

#2676 [ci] CHANGELOG for Node/Standalone firefox browser versions with Grid 4.29.0
  CHANGELOG/4.29.0/firefox_135.md
Labels: Review effort 1/5

#2681 K8s: Bump new KEDA image for feature preview
  .keda/README.md
  .keda/results_test_k8s_autoscaling_deployment_count.md
  .keda/results_test_k8s_autoscaling_deployment_count_in_chaos.md
  .keda/results_test_k8s_autoscaling_deployment_count_with_node_max_sessions.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_in_chaos.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_with_node_max_sessions.md
  .keda/scalers/selenium-grid-scaler.md
  .keda/scalers/selenium_grid_scaler.go
  .keda/scalers/selenium_grid_scaler_test.go
  Makefile
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/Chart.yaml
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/values.yaml
  tests/charts/ci/DeploymentAutoscaling-values.yaml
  tests/charts/ci/JobAutoscaling-values.yaml
  tests/charts/make/chart_test.sh
Labels: Review effort 3/5

#2686 K8s: Update Helm configs for setting Node custom capabilities
  Makefile
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/values.yaml
  tests/charts/make/chart_test.sh
  tests/charts/templates/render/dummy.yaml
  tests/charts/templates/render/dummy_solution.yaml
Labels: Review effort 2/5
