Repository SeleniumHQ/docker-selenium, pull requests merged in 2025-01, with the labels that each got.

#2546 Docker: Collect JVM heap dump in case server run into error
  Base/Dockerfile
  Base/handle_heap_dump.sh
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/values.yaml
  tests/charts/ci/DeploymentAutoscaling-values.yaml
  tests/charts/ci/JobAutoscaling-values.yaml
  tests/charts/ci/NoAutoscaling-values.yaml
  tests/charts/ci/base-auth-ingress-values.yaml
  tests/charts/make/chart_test.sh
Labels: Review effort [1-5]: 3

#2547 Docker: Install Firefox from multiple package types
  Makefile
  NodeFirefox/Dockerfile
  NodeFirefox/install-firefox-package.sh
Labels: Review effort [1-5]: 3

#2553 [ci] Fix workflows stable for ARM64 tests
  .circleci/config.yml
  .github/workflows/helm-chart-test.yml
  tests/SeleniumTests/__init__.py
  tests/charts/make/chart_test.sh
  tests/docker-compose-v3-test-parallel.yml
Labels: Review effort [1-5]: 2

#2558 [ci] Upload autoscaling in K8s test results
  .keda/results_test_k8s_autoscaling_deployment_count.md
  .keda/results_test_k8s_autoscaling_deployment_count_in_chaos.md
  .keda/results_test_k8s_autoscaling_deployment_count_with_node_max_sessions.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_in_chaos.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_with_node_max_sessions.md
Labels: Review effort [1-5]: 2

#2560 [ci] Try runner Ubuntu 24.04
  .circleci/config.yml
  .github/workflows/build-test.yml
  .github/workflows/docker-test.yml
  .github/workflows/helm-chart-release.yml
  .github/workflows/helm-chart-test.yml
  .github/workflows/k8s-scaling-test.yml
  .github/workflows/label-commenter.yml
  .github/workflows/lock.yml
  .github/workflows/rerun-failed.yml
  .github/workflows/scan-dockerfile.yml
  .github/workflows/update-chart-readme.yml
  .github/workflows/update-dev-beta-browser-images.yml
Labels: Review effort [1-5]: 1

#2565 Docker: Video uploader process is spawned by env var flag SE_VIDEO_UPLOAD_ENABLED
  README.md
  Video/uploader.conf
Labels: Review effort [1-5]: 1

#2564 [docs] Generate list environment variables README automatically
  Base/Dockerfile
  Distributor/Dockerfile
  ENV_VARIABLES.md
  Hub/Dockerfile
  Makefile
  NodeBase/Dockerfile
  README.md
  Router/Dockerfile
  SessionQueue/Dockerfile
  Sessions/Dockerfile
  Standalone/Dockerfile
  StandaloneDocker/Dockerfile
  Video/Dockerfile
  scripts/generate_list_env_vars/description.yaml
  scripts/generate_list_env_vars/extract_env.py
  scripts/generate_list_env_vars/value.yaml
  tests/charts/bootstrap.sh
  tests/requirements.txt
Labels: Review effort [1-5]: 3

#2575 K8s: Bump KEDA patch version
  Makefile
  charts/selenium-grid/multiple-nodes-platform.yaml
  tests/SeleniumTests/__init__.py
  tests/charts/ci/local-pvc.yaml
  tests/charts/make/chart_test.sh
Labels: Review effort [1-5]: 2

#2580 [Helm Chart] only add annotations stanza if they are annotations to add
  charts/selenium-grid/templates/chrome-node-scaledjobs.yaml
  charts/selenium-grid/templates/edge-node-scaledjob.yaml
  charts/selenium-grid/templates/firefox-node-scaledjob.yaml
  charts/selenium-grid/templates/relay-node-scaledjobs.yaml
Labels: Review effort [1-5]: 1

#2577 Docker: Unified the env var `$CONFIG_FILE` from Base
  Base/Dockerfile
  NodeBase/Dockerfile
  NodeDocker/start-selenium-grid-docker.sh
  Sessions/Dockerfile
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
Labels: Review effort [1-5]: 3

#2586 Docker: FFmpeg with audio devices support (Pulse, Alsa)
  .ffmpeg/Dockerfile
  ENV_VARIABLES.md
  Router/Dockerfile
  Video/Dockerfile
  Video/video.sh
  scripts/generate_list_env_vars/description.yaml
  scripts/generate_list_env_vars/extract_env.py
  scripts/generate_list_env_vars/value.yaml
Labels: Review effort [1-5]: 3

#2591 K8s: Remove .svc.cluster.local from component host using service name
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/event-bus-configmap.yaml
  charts/selenium-grid/templates/node-configmap.yaml
  tests/charts/templates/test.py
Labels: Review effort [1-5]: 2

#2593 K8s: Update template for service configs
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/README.md
  charts/selenium-grid/configs/scrape/selenium-grid.yaml
  charts/selenium-grid/templates/chrome-node-service.yaml
  charts/selenium-grid/templates/distributor-deployment.yaml
  charts/selenium-grid/templates/distributor-service.yaml
  charts/selenium-grid/templates/edge-node-service.yaml
  charts/selenium-grid/templates/event-bus-configmap.yaml
  charts/selenium-grid/templates/event-bus-service.yaml
  charts/selenium-grid/templates/firefox-node-service.yaml
  charts/selenium-grid/templates/hub-service.yaml
  charts/selenium-grid/templates/monitoring-exporter-service.yaml
  charts/selenium-grid/templates/node-configmap.yaml
  charts/selenium-grid/templates/relay-node-service.yaml
  charts/selenium-grid/templates/router-deployment.yaml
  charts/selenium-grid/templates/router-service.yaml
  charts/selenium-grid/templates/session-map-service.yaml
  charts/selenium-grid/templates/session-queue-service.yaml
  charts/selenium-grid/values.yaml
  tests/charts/templates/render/dummy.yaml
  tests/charts/templates/render/dummy_solution.yaml
Labels: Review effort [1-5]: 2

#2596 K8s: Update default component ConfigMap and resources limits
  Distributor/start-selenium-grid-distributor.sh
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/_nameHelpers.tpl
  charts/selenium-grid/templates/distributor-configmap.yaml
  charts/selenium-grid/templates/event-bus-configmap.yaml
  charts/selenium-grid/templates/logging-configmap.yaml
  charts/selenium-grid/templates/node-configmap.yaml
  charts/selenium-grid/templates/router-configmap.yaml
  charts/selenium-grid/templates/secrets.yaml
  charts/selenium-grid/templates/server-configmap.yaml
  charts/selenium-grid/templates/session-map-configmap.yaml
  charts/selenium-grid/templates/session-queue-configmap.yaml
  charts/selenium-grid/values.yaml
Labels: Review effort [1-5]: 3

#2594 K8s: Fix chart template for relay node
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/Chart.yaml
  charts/selenium-grid/templates/relay-node-deployment.yaml
  tests/charts/templates/render/dummy.yaml
  tests/charts/templates/render/dummy_solution.yaml
Labels: Review effort [1-5]: 2

#2598 Docker: Unified node config session-timeout from generated TOML file
  NodeBase/generate_config
  NodeBase/start-selenium-node.sh
  Standalone/generate_config
Labels: Review effort [1-5]: 2

#2599 Release Grid 4.28.0
  Base/Dockerfile
  Makefile
Labels: Review effort [1-5]: 2

#2602 Docker: Video record extract last session from json response
  Video/video.sh
  Video/video_graphQLQuery.sh
Labels: Review effort [1-5]: 2

#2603 Revert changes in video recorder
  .github/workflows/build-test.yml
  .github/workflows/helm-chart-test.yml
  Video/video.sh
  Video/video_graphQLQuery.sh
Labels: Review effort [1-5]: 2

#2606 [ci] Upload autoscaling in K8s test results
  .keda/results_test_k8s_autoscaling_deployment_count.md
  .keda/results_test_k8s_autoscaling_deployment_count_in_chaos.md
  .keda/results_test_k8s_autoscaling_deployment_count_with_node_max_sessions.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_in_chaos.md
  .keda/results_test_k8s_autoscaling_job_count_strategy_default_with_node_max_sessions.md
Labels: Review effort [1-5]: 2

#2618 feat: added nodeSelector for keda patch pods
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml
  charts/selenium-grid/values.yaml
Labels: Review effort [1-5]: 1

#2624 SE_NODE_STEREOTYPE_EXTRA to append custom capabilities to default Node stereotype
  ENV_VARIABLES.md
  NodeBase/Dockerfile
  NodeBase/generate_config
  NodeBase/json_merge.py
  README.md
  Standalone/generate_config
  scripts/generate_list_env_vars/description.yaml
  scripts/generate_list_env_vars/extract_env.py
  scripts/generate_list_env_vars/value.yaml
  tests/docker-compose-v3-test-parallel.yml
  tests/docker-compose-v3-test-standalone.yml
Labels: Review effort [1-5]: 3
