Repository SeleniumHQ/docker-selenium, pull requests merged in 2025-08, with the labels that each got.

#2912 Missing tolerations for keda patched jobs #2911
  charts/selenium-grid/templates/patch-keda/delete-keda-objects-job.yaml
  charts/selenium-grid/templates/patch-keda/patch-keda-objects-job.yaml
Labels: Review effort 2/5

#2868 migrate validate_endpoint to python
  Video/validate_endpoint.py
  Video/validate_endpoint.sh
  Video/video.sh
Labels: Review effort 3/5

#2918 [ci] Update K8s version in test workflow
  .github/workflows/helm-chart-test.yml
  .github/workflows/k8s-scaling-test.yml
Labels: Review effort 1/5

#2922 [ci] CHANGELOG for Node/Standalone firefox browser versions with Grid 4.34.0
  CHANGELOG/4.34.0/firefox_100.md
  CHANGELOG/4.34.0/firefox_101.md
  CHANGELOG/4.34.0/firefox_102.md
  CHANGELOG/4.34.0/firefox_103.md
  CHANGELOG/4.34.0/firefox_104.md
  CHANGELOG/4.34.0/firefox_105.md
  CHANGELOG/4.34.0/firefox_106.md
  CHANGELOG/4.34.0/firefox_107.md
  CHANGELOG/4.34.0/firefox_108.md
  CHANGELOG/4.34.0/firefox_109.md
  CHANGELOG/4.34.0/firefox_110.md
  CHANGELOG/4.34.0/firefox_111.md
  CHANGELOG/4.34.0/firefox_112.md
  CHANGELOG/4.34.0/firefox_113.md
  CHANGELOG/4.34.0/firefox_114.md
  CHANGELOG/4.34.0/firefox_115.md
  CHANGELOG/4.34.0/firefox_116.md
  CHANGELOG/4.34.0/firefox_117.md
  CHANGELOG/4.34.0/firefox_118.md
  CHANGELOG/4.34.0/firefox_119.md
  CHANGELOG/4.34.0/firefox_120.md
  CHANGELOG/4.34.0/firefox_121.md
  CHANGELOG/4.34.0/firefox_122.md
  CHANGELOG/4.34.0/firefox_123.md
  CHANGELOG/4.34.0/firefox_124.md
  CHANGELOG/4.34.0/firefox_125.md
  CHANGELOG/4.34.0/firefox_126.md
  CHANGELOG/4.34.0/firefox_127.md
  CHANGELOG/4.34.0/firefox_128.md
  CHANGELOG/4.34.0/firefox_129.md
  CHANGELOG/4.34.0/firefox_130.md
  CHANGELOG/4.34.0/firefox_131.md
  CHANGELOG/4.34.0/firefox_132.md
  CHANGELOG/4.34.0/firefox_133.md
  CHANGELOG/4.34.0/firefox_134.md
  CHANGELOG/4.34.0/firefox_135.md
  CHANGELOG/4.34.0/firefox_136.md
  CHANGELOG/4.34.0/firefox_137.md
  CHANGELOG/4.34.0/firefox_138.md
  CHANGELOG/4.34.0/firefox_139.md
  CHANGELOG/4.34.0/firefox_98.md
  CHANGELOG/4.34.0/firefox_99.md
  tests/build-backward-compatible/browser-matrix.yml
  tests/build-backward-compatible/firefox-matrix.yml
Labels: Review effort 1/5
