Repository SeleniumHQ/docker-selenium, pull requests merged in 2025-04, with the labels that each got.

#2658 migrate video_gridUrl.sh to python
  Video/Dockerfile
  Video/video.sh
  Video/video_graphQLQuery.sh
  Video/video_gridUrl.py
  Video/video_gridUrl.sh
Labels: Review effort 2/5

#2748 Docker: Setup Python venv in Base image for utilities
  Base/Dockerfile
  Base/entry_point.sh
  NodeBase/Dockerfile
  Video/Dockerfile
  Video/entry_point.sh
Labels: Review effort 2/5

#2742 Docker: Improve video recorder process
  .github/actions/get-latest-upstream/action.yml
  .github/workflows/docker-test.yml
  Makefile
  Video/video.sh
  tests/charts/make/chart_test.sh
Labels: Review effort 1/5

#2754 Breaking changes: Node/Standalone Docker config path change to `/opt/selenium/docker.toml`
  ENV_VARIABLES.md
  NodeDocker/Dockerfile
  NodeDocker/config.toml
  README.md
  StandaloneDocker/start-selenium-grid-docker.sh
  docker-compose-v3-dynamic-grid.yml
  docker-compose-v3-video-upload-dynamic-grid.yml
  scripts/generate_list_env_vars/value.yaml
  tests/docker-compose-v3-test-node-docker.yaml
  tests/docker-compose-v3-test-standalone-docker.yaml
Labels: Review effort 2/5

#2726 Allow adding custom external jars to classpath
  Distributor/start-selenium-grid-distributor.sh
  ENV_VARIABLES.md
  EventBus/start-selenium-grid-eventbus.sh
  Hub/start-selenium-grid-hub.sh
  NodeBase/start-selenium-node.sh
  NodeDocker/start-selenium-grid-docker.sh
  Router/start-selenium-grid-router.sh
  SessionQueue/start-selenium-grid-session-queue.sh
  Sessions/start-selenium-grid-sessions.sh
  Standalone/start-selenium-standalone.sh
  StandaloneDocker/start-selenium-grid-docker.sh
Labels: Review effort 2/5

#2760 K8s: Strictly handle `basicAuth.enabled` in template
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/templates/basic-auth-secret.yaml
  charts/selenium-grid/templates/distributor-deployment.yaml
  charts/selenium-grid/templates/event-bus-deployment.yaml
  charts/selenium-grid/templates/hub-deployment.yaml
  charts/selenium-grid/templates/patch-keda/patch-keda-objects-cm.yaml
  charts/selenium-grid/templates/router-deployment.yaml
  charts/selenium-grid/templates/session-map-deployment.yaml
  charts/selenium-grid/templates/session-queue-deployment.yaml
  charts/selenium-grid/templates/trigger-auth.yaml
Labels: Review effort 2/5

#2763 K8s: Add template for file browser video records service
  charts/selenium-grid/CONFIGURATION.md
  charts/selenium-grid/templates/_nameHelpers.tpl
  charts/selenium-grid/templates/video-manager/file-browser-deployment.yaml
  charts/selenium-grid/templates/video-manager/file-browser-ingress.yaml
  charts/selenium-grid/templates/video-manager/file-browser-service.yaml
  charts/selenium-grid/values.yaml
  tests/charts/refValues/simplex-docker-desktop.yaml
Labels: Review effort 2/5, Possible security concern

#2762 Docker: Replace static value by env variable in Supervisord config
  Base/Dockerfile
  Base/supervisord.conf
Labels: Review effort 1/5

#2766 [ci] CHANGELOG for Node/Standalone edge browser versions with Grid 4.31.0
  CHANGELOG/4.31.0/edge_114.md
  CHANGELOG/4.31.0/edge_115.md
  CHANGELOG/4.31.0/edge_116.md
  CHANGELOG/4.31.0/edge_117.md
  CHANGELOG/4.31.0/edge_118.md
  CHANGELOG/4.31.0/edge_119.md
  CHANGELOG/4.31.0/edge_120.md
  CHANGELOG/4.31.0/edge_121.md
  CHANGELOG/4.31.0/edge_122.md
  CHANGELOG/4.31.0/edge_123.md
  CHANGELOG/4.31.0/edge_124.md
  CHANGELOG/4.31.0/edge_125.md
  CHANGELOG/4.31.0/edge_126.md
  CHANGELOG/4.31.0/edge_127.md
  CHANGELOG/4.31.0/edge_128.md
  CHANGELOG/4.31.0/edge_129.md
  CHANGELOG/4.31.0/edge_130.md
  CHANGELOG/4.31.0/edge_131.md
  CHANGELOG/4.31.0/edge_132.md
  CHANGELOG/4.31.0/edge_133.md
  CHANGELOG/4.31.0/edge_134.md
Labels: Review effort 1/5

#2777 k8s: Add ability to config trigger name
  charts/selenium-grid/templates/_helpers.tpl
  charts/selenium-grid/values.yaml
Labels: Review effort 1/5

#2779 Docker: Update basic auth headers in util scripts
  Base/check-grid.sh
  Video/validate_endpoint.sh
  Video/video.sh
  Video/video_graphQLQuery.sh
  charts/selenium-grid/configs/distributor/distributorProbe.sh
  charts/selenium-grid/configs/node/nodeGridUrl.sh
  charts/selenium-grid/configs/node/nodePreStop.sh
  charts/selenium-grid/configs/node/nodeProbe.sh
  charts/selenium-grid/configs/router/routerProbe.sh
  tests/CDPTests/bootstrap.sh
Labels: Review effort 2/5

#2783 Docker: Add more logs to video container
  Video/video.sh
Labels: Review effort 2/5
